# Generated by Django 4.1.7 on 2023-03-05 15:19

import api.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisor",
            fields=[
                ("advisor_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=15)),
                ("video", models.CharField(max_length=512)),
                ("about", models.CharField(max_length=1024)),
                ("experience", models.CharField(max_length=512)),
                (
                    "profile_picture",
                    models.ImageField(upload_to=api.models.upload_path),
                ),
                ("quote", models.CharField(max_length=1024)),
                ("region_of_operation", models.CharField(max_length=512)),
                ("risk_rate", models.DecimalField(decimal_places=2, max_digits=3)),
                ("success_rate", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "profile_picture",
                    models.ImageField(upload_to=api.models.upload_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("logo", models.ImageField(upload_to=api.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("ratings", models.DecimalField(decimal_places=2, max_digits=2)),
                ("comments", models.CharField(max_length=512)),
                ("photo", models.ImageField(upload_to=api.models.upload_path)),
                ("create_date", models.DateField()),
                ("update_date", models.DateField()),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
                (
                    "fk_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=512)),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCompany",
            fields=[
                (
                    "service_company_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fk_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
                (
                    "fk_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewHighlight",
            fields=[
                (
                    "review_highlight_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
                (
                    "fk_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                (
                    "fk_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("follow_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
                (
                    "fk_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("certificate_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("certified_by", models.CharField(max_length=50)),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessStatistics",
            fields=[
                ("business_id", models.AutoField(primary_key=True, serialize=False)),
                ("number_of_clients", models.IntegerField()),
                ("number_of_deals", models.IntegerField()),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=60, unique=True)),
                ("type_of_user", models.BooleanField(default=True)),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
                (
                    "fk_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
