# Generated by Django 4.1.7 on 2023-03-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_fk_advisor_alter_user_fk_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="risk_rate",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="advisor",
            name="success_rate",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
