# Generated by Django 4.1.7 on 2023-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_advisor_risk_rate_alter_advisor_success_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessstatistics",
            name="portfolio",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="businessstatistics",
            name="profitability",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
