# Generated by Django 4.1.7 on 2023-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_businessstatistics_portfolio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessstatistics",
            name="portfolio",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
