# Generated by Django 4.1.7 on 2023-03-05 16:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_businessstatistics_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to=api.models.upload_path),
        ),
    ]
