# Generated by Django 4.1.7 on 2023-03-05 16:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_client_phone_alter_client_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(null=True, upload_to=api.models.upload_path),
        ),
    ]
