# Generated by Django 4.1.7 on 2023-03-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ratings",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
