# Generated by Django 4.1.7 on 2023-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_review_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="license_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="advisor",
            name="response_rate",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
