# Generated by Django 4.1.7 on 2023-03-16 19:31

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_advisor_license_number_advisor_response_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fk_advisor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fk_client",
        ),
        migrations.AddField(
            model_name="advisor",
            name="fk_user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="fk_user",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(default=None, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name="client",
            name="profile_picture",
            field=models.ImageField(upload_to=api.models.upload_path),
        ),
    ]
