# Generated by Django 4.1.7 on 2023-03-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_advisor_email_remove_advisor_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("create_date", models.DateField()),
                ("create_time", models.TimeField()),
                ("update_date", models.DateField()),
                ("update_time", models.TimeField()),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("canceled", "canceled"), ("completed", "completed")],
                        max_length=10,
                    ),
                ),
                (
                    "fk_advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
                    ),
                ),
                (
                    "fk_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.client"
                    ),
                ),
            ],
        ),
    ]
