# Generated by Django 4.1.7 on 2023-03-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("canceled", "canceled"), ("completed", "completed")],
                max_length=10,
                null=True,
            ),
        ),
    ]
