# Generated by Django 4.1.7 on 2023-03-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="duration",
            field=models.TimeField(default="00:00:15"),
        ),
    ]
