# Generated by Django 4.1.7 on 2023-03-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_appointment_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                ("otpId", models.AutoField(primary_key=True, serialize=False)),
                ("otp", models.CharField(max_length=8)),
                ("email", models.EmailField(default="abc@xyz.com", max_length=254)),
                ("create_time", models.DateTimeField()),
                ("expiry_time", models.DateTimeField()),
                ("verified", models.BooleanField(default=False)),
                ("used", models.BooleanField(default=False)),
                (
                    "fk_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
