# Generated by Django 4.1.7 on 2023-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="url",
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
