# Generated by Django 4.1.7 on 2023-03-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_advisor_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('service_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('fk_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
