# Generated by Django 4.1.7 on 2023-04-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_serviceclient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisor",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="advisor",
            name="user_name",
            field=models.CharField(default="sidfinlit", max_length=25),
        ),
    ]
