# Generated by Django 4.1.7 on 2023-04-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_advisor_profile_picture_advisor_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="user_name",
            field=models.CharField(default="sidfinlit", max_length=25, unique=True),
        ),
    ]
