# Generated by Django 4.1.7 on 2023-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_advisor_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Urls",
            fields=[
                ("url_id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=25)),
            ],
        ),
    ]
