# Generated by Django 4.1.7 on 2023-04-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_urls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
