# Generated by Django 4.1.7 on 2023-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="type_of_user",
            new_name="is_advisor",
        ),
        migrations.AddField(
            model_name="user",
            name="is_whatsapp",
            field=models.BooleanField(default=True),
        ),
    ]
