# Generated by Django 4.1.7 on 2023-04-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_rename_type_of_user_user_is_advisor_user_is_whatsapp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="profile_picture",
        ),
    ]
