# Generated by Django 4.1.7 on 2023-04-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_client_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='url',
            new_name='meet_url',
        ),
    ]
