# Generated by Django 4.1.7 on 2023-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_client_profile_picture"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("fk_client", "fk_advisor"), name="unique_key_client_advisor"
            ),
        ),
    ]
