# Generated by Django 4.1.7 on 2023-04-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_follow_unique_key_client_advisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="create_time",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="update_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="update_time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
