# Generated by Django 4.1.7 on 2023-04-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_url_advisor_meet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
