# Generated by Django 4.1.7 on 2023-04-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_appointment_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="fk_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
