# Generated by Django 4.1.7 on 2023-04-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_user_surname"),
        ("api", "0027_alter_client_fk_user"),
    ]

    operations = []
