# Generated by Django 4.1.7 on 2023-04-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_0026_user_surname_0027_alter_client_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(default='prospect', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Canada', max_length=255),
            preserve_default=False,
        ),
    ]
