# Generated by Django 4.1.7 on 2023-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_client_category_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='Mr.', max_length=7),
        ),
    ]
