# Generated by Django 4.1.7 on 2023-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='address',
        ),
        migrations.AddField(
            model_name='advisor',
            name='is_team_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.CharField(default='Nothing is impossible', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.CharField(default='Nothing is impossible', max_length=1024),
            preserve_default=False,
        ),
    ]
