# Generated by Django 4.1.7 on 2023-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_advisor_address_advisor_is_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='Mr.', max_length=7, null=True),
        ),
    ]
