# Generated by Django 4.1.7 on 2023-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_user_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFields',
            fields=[
                ('template_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('fields', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=50)),
                ('template_url', models.CharField(max_length=512)),
            ],
        ),
    ]
