# Generated by Django 4.1.7 on 2023-04-12 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="fk_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
