# Generated by Django 4.1.7 on 2023-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_client_comment_alter_client_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="category",
            field=models.CharField(
                blank=True, default="prospect", max_length=25, null=True
            ),
        ),
    ]
