# Generated by Django 4.1.7 on 2023-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_client_category_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSales',
            fields=[
                ('contact_sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('business', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('postal_code', models.IntegerField()),
            ],
        ),
    ]
