# Generated by Django 4.1.7 on 2023-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_contactsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsales',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
