# Generated by Django 4.1.7 on 2023-04-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_paymentbilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='user_name',
        ),
    ]
