# Generated by Django 4.1.7 on 2023-04-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_advisor_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='app_password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='template',
            field=models.IntegerField(default=1),
        ),
    ]
