# Generated by Django 4.1.7 on 2023-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_advisor_app_password_advisor_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_name',
            field=models.CharField(default='Brief Discussion', max_length=255),
            preserve_default=False,
        ),
    ]
