# Generated by Django 4.1.7 on 2023-04-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_appointment_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_name',
            field=models.CharField(default='Brief Discussion', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.TimeField(default='00:15:00'),
        ),
    ]
