# Generated by Django 4.1.7 on 2023-04-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_appointment_appointment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('active', 'active'), ('completed', 'completed')], default='active', max_length=10, null=True),
        ),
    ]
