# Generated by Django 4.1.7 on 2023-04-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('working_hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_time', models.IntegerField()),
                ('dayName', models.CharField(max_length=20, null=True)),
                ('advisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
