# Generated by Django 4.1.7 on 2023-04-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_workinghour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghour',
            old_name='advisor_id',
            new_name='fk_advisor',
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='dayName',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
            preserve_default=False,
        ),
    ]
