# Generated by Django 4.1.7 on 2023-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_rename_advisor_id_workinghour_fk_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=10, null=True),
        ),
    ]
