# Generated by Django 4.1.7 on 2023-05-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_workinghour_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
