# Generated by Django 4.1.7 on 2023-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='facebook',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='instagram',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
