# Generated by Django 4.1.7 on 2023-05-06 13:17

import api.models.Services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_advisor_facebook_advisor_instagram_advisor_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to=api.models.Services.upload_path),
        ),
    ]
