# Generated by Django 4.1.7 on 2023-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsales',
            name='postal_code',
            field=models.CharField(max_length=100),
        ),
    ]
