# Generated by Django 4.1.7 on 2023-05-09 10:43

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_contactsales_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_color', models.CharField(max_length=100)),
                ('intro_bg_color', models.CharField(max_length=100)),
                ('section_bg_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(default=None, upload_to=api.models.Services.upload_path)),
            ],
        ),
        migrations.DeleteModel(
            name='TemplateFields',
        ),
        migrations.AddField(
            model_name='advisor',
            name='tm_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='fk_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor'),
        ),
    ]
