# Generated by Django 4.1.7 on 2023-05-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_custom_teammember_delete_templatefields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='fk_advisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.advisor'),
            preserve_default=False,
        ),
    ]
