# Generated by Django 4.1.7 on 2023-05-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_advisor_fk_custom_custom_fk_advisor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='TeamGallery',
        ),
        migrations.RenameField(
            model_name='teamgallery',
            old_name='team_member_id',
            new_name='team_gallery_id',
        ),
    ]
