# Generated by Django 4.1.7 on 2023-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_rename_teammember_teamgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='cards_icon_bg',
            field=models.CharField(default='#f3edf7', max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='intro_bg_color',
            field=models.CharField(default='#f3edf7', max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='primary_color',
            field=models.CharField(default='#e025e5', max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='section_bg_color',
            field=models.CharField(default='#f3edf7', max_length=100),
        ),
    ]
