# Generated by Django 4.1.7 on 2023-05-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_custom_cards_icon_bg_alter_custom_intro_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='fk_advisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.advisor'),
        ),
    ]
