# Generated by Django 4.1.7 on 2023-05-16 09:49

import api.models.Services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_custom_fk_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='logo',
            field=models.ImageField(default=None, upload_to=api.models.Services.upload_path),
        ),
    ]
