# Generated by Django 4.1.7 on 2023-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_advisor_description_advisor_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReview',
            fields=[
                ('public_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('comments', models.CharField(blank=True, max_length=512, null=True)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
