# Generated by Django 4.1.7 on 2023-05-25 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_publicreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='completed_session',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='passive_generated_income',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='professional_trained',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='team_member_count',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='total_seminar',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamgallery',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teamgallery',
            name='name',
            field=models.CharField(default='Jaynos Slynt', max_length=255),
            preserve_default=False,
        ),
    ]
