# Generated by Django 4.1.7 on 2023-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_advisor_completed_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='completed_session',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='professional_trained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='total_seminar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
