# Generated by Django 4.1.7 on 2023-05-28 05:43

import api.models.Services
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0064_alter_advisor_completed_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status',
                 models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('feature_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorGallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status',
                 models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('pictures', models.ImageField(default=None, upload_to=api.models.Services.upload_path)),
                ('column_number', models.IntegerField()),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                (
                    'status',
                    models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('package_name', models.CharField(max_length=214)),
            ],
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('package_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status',
                 models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('fk_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feature')),
                ('fk_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
            ],
        ),

        migrations.RemoveField(
            model_name='advisor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='template',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='tm_photo',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='story',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[(0, 'review'), (1, 'story')], default='review', max_length=10),
        ),
        
    ]
