# Generated by Django 4.1.7 on 2023-05-28 18:50
import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_feature_remove_advisor_role_remove_advisor_template_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='review',
            name='story',
        ),
        migrations.RemoveField(
            model_name='review',
            name='type',
        ),
        
        migrations.AddField(
            model_name='teamgallery',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),

    ]
