# Generated by Django 4.1.7 on 2023-05-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_review_story_remove_review_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgallery',
            name='heading',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
