# Generated by Django 4.1.7 on 2023-05-31 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_teamgallery_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadGeneration',
            fields=[
                ('generation_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=512)),
                ('device', models.CharField(max_length=512)),
            ],
        ),
    ]
