# Generated by Django 4.1.7 on 2023-06-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_leadgeneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsales',
            name='business',
        ),
        migrations.RemoveField(
            model_name='contactsales',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='risk_rate',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='success_rate',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='video',
        ),
    ]
