# Generated by Django 4.1.7 on 2023-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_remove_contactsales_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsales',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
