# Generated by Django 4.1.7 on 2023-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_contactsales_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='platform',
            field=models.CharField(blank=True, default='gmail', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guests',
            field=models.TextField(blank=True, default=[], null=True),
        ),

    ]
