# Generated by Django 4.1.7 on 2023-06-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_advisor_platform_appointment_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='license_number',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='about',
            field=models.CharField(default='Empowering families for prosperous futures and fulfilling dreams through trusted financial guidance.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='experience',
            field=models.CharField(default=3, max_length=512),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='meet_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='quote',
            field=models.CharField(default='Cultivating a shared journey towards prosperous futures, empowering both individuals and their families.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='region_of_operation',
            field=models.CharField(default='Canada', max_length=512),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='response_rate',
            field=models.DecimalField(decimal_places=1, default=90, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='businessstatistics',
            name='number_of_clients',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='businessstatistics',
            name='number_of_deals',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='businessstatistics',
            name='portfolio',
            field=models.CharField(default='1 million', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='businessstatistics',
            name='profitability',
            field=models.DecimalField(decimal_places=2, default=86, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certified_by',
            field=models.CharField(default='Government of Canada', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='Home Financing', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(default='Discover the transformative power of proven investment strategies, offering guidance toward financial independence and the accumulation of wealth through informed decision - making.', max_length=512),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='Powerful tactics for achieving home ownership success.', max_length=50),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='completed_session',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='description',
            field=models.CharField(blank=True,
                                   default='Empowering families for prosperous futures and fulfilling dreams through trusted financial guidance.',
                                   max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='fk_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.package'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='passive_generated_income',
            field=models.CharField(blank=True, default='5 Million', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='professional_trained',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='team_member_count',
            field=models.CharField(blank=True, default=25, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='total_seminar',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
    ]
