# Generated by Django 4.1.7 on 2023-06-11 14:37

import api.models.Services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_advisor_license_number_alter_advisor_about_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='img/Name/leapon_dummy.jpg', upload_to=api.models.Services.upload_path),
        ),
    ]
