# Generated by Django 4.1.7 on 2023-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.CharField(default='Discover the transformative power of proven investment strategies, offering'
                                           ' guidance toward financial independence and the accumulation of wealth '
                                           'through informed decision - making.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='Powerful tactics for achieving home ownership success.', max_length=512),
        ),
    ]
