# Generated by Django 4.1.7 on 2023-06-14 11:45

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_service_name_service_desc'),
    ]

    operations = [

        migrations.AlterField(
            model_name='advisor',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_advisor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='team_members_as_advisor', to='api.advisor')),
                ('fk_member', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='team_members_as_member', to='api.advisor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('fk_member', 'fk_advisor'), name='unique_member_advisor'),
        ),
    ]
