# Generated by Django 4.1.7 on 2023-06-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_advisor_logo_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),

    ]
