# Generated by Django 4.1.7 on 2023-06-21 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_appointment_meet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='fk_advisor',
        ),
        migrations.CreateModel(
            name='AdvisorAppointment',
            fields=[
                ('advisor_appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active',
                                            max_length=10)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
                ('fk_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     to='api.appointment')),
            ],
        ),
    ]
