# Generated by Django 4.1.7 on 2023-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_appointment_fk_advisor_advisor_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorappointment',
            name='owner',
            field=models.BooleanField(default=False),
        ),

        migrations.AddConstraint(
            model_name='advisorappointment',
            constraint=models.UniqueConstraint(fields=('fk_appointment', 'fk_advisor'),
                                               name='unique_key_appointment_advisor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('active', 'active'), ('completed', 'completed')],
                                   default='active', max_length=10),
        ),
    ]
