# Generated by Django 4.1.7 on 2023-06-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_constraint_unique_key_appointment_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='steps',
            field=models.JSONField(default=list, max_length=5),
        ),
    ]
