# Generated by Django 4.1.7 on 2023-07-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_follow_is_complete_follow_steps'),
    ]

    operations = [

        migrations.AlterField(
            model_name='advisor',
            name='app_password',
            field=models.CharField(blank=True, default='', max_length=16),
        ),

    ]
