# Generated by Django 4.1.7 on 2023-07-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_advisor_app_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghour',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workinghour',
            name='start_time',
        ),

        migrations.AddField(
            model_name='workinghour',
            name='working_hour',
            field=models.JSONField(default=list),
            preserve_default=False,
        ),

    ]
