# Generated by Django 4.1.7 on 2023-07-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_workinghour_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='fiq',
            field=models.JSONField(default=list),
        ),

    ]
