# Generated by Django 4.1.7 on 2023-07-25 07:36

import api.models.Services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_follow_score'),
    ]

    operations = [

        migrations.AddField(
            model_name='user',
            name='marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=512)),
                ('body', models.CharField(max_length=1024)),
                ('subtitle', models.CharField(blank=True, max_length=512, null=True)),
                ('blog_cover', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path)),
                ('author_image', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path)),
                ('author_description', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('fk_user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
    ]
