# Generated by Django 4.1.7 on 2023-07-25 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_blog_and_user_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=512)),
                ('device', models.CharField(max_length=512)),
            ],
        ),
    ]
