# Generated by Django 4.1.7 on 2023-08-02 13:56

import api.models.Services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_blog_created_date_blog_min_to_read_blog_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_description',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_cover',
            field=models.ImageField(default=None, upload_to=api.models.Services.upload_path),
        ),
    ]
