# Generated by Django 4.1.7 on 2023-08-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_blog_author_description_alter_blog_blog_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_whatsapp',
        ),
    ]
