# Generated by Django 4.1.7 on 2023-08-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_user_is_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstatistics',
            name='number_of_clients',
            field=models.CharField(default=25, max_length=25),
        ),
        migrations.AlterField(
            model_name='businessstatistics',
            name='number_of_deals',
            field=models.CharField(default=45, max_length=25),
        ),
    ]
