# Generated by Django 4.1.7 on 2023-08-24 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_businessstatistics_number_of_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
