# Generated by Django 4.1.7 on 2023-10-07 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(max_length=512)),
            ],
        ),
    ]
