# Generated by Django 4.1.7 on 2023-10-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_digitalcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalcard',
            name='address',
        ),
    ]
