# Generated by Django 4.1.7 on 2023-10-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_digitalcard_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
