# Generated by Django 4.1.7 on 2023-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_digitalcard_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='organization_size',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='purpose',
            field=models.TextField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='issues',
            field=models.CharField(default='website', max_length=512),
            preserve_default=False,
        ),
    ]
