# Generated by Django 4.1.7 on 2023-10-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_advisor_organization_size_advisor_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
