# Generated by Django 4.1.7 on 2023-10-18 11:35

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_digitalcard_profession'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='digitalcard',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
      
    ]
