# Generated by Django 4.1.7 on 2023-10-24 12:02

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_website'),
    ]

    operations = [
      
        
        migrations.AlterField(
            model_name='digitalcard',
            name='email',
            field=models.EmailField(max_length=254),
        ),
     
    
    ]
