# Generated by Django 4.1.7 on 2023-11-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='digitalcard',
            name='website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),

    ]
