# Generated by Django 4.1.7 on 2023-11-16 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_digital_card_website'),
    ]

    operations = [

        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1024)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
