# Generated by Django 4.1.7 on 2023-12-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_exchange_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCardEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
