# Generated by Django 4.1.7 on 2023-12-11 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_digitalcardemail_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcardemail',
        name='fk_advisor',
        field=models.ForeignKey(default=None, null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Advisor'),
        ),
       
    ]
