# Generated by Django 4.1.7 on 2024-01-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_digitalcardemail_fk_advisor_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
