# Generated by Django 4.1.7 on 2024-01-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_advisor_access_token_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='access_token',
            new_name='google_access_token',
        ),
        
    ]
