# Generated by Django 4.1.7 on 2024-01-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_rename_access_token_advisor_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
           ]
