# Generated by Django 4.1.7 on 2024-01-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_advisor_google_refresh_token_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='google_auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
       
    ]
