# Generated by Django 4.1.7 on 2024-01-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_advisor_google_auth_code_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='google_auth_code',
        ),
        
    ]
