# Generated by Django 4.1.7 on 2024-01-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_remove_advisor_google_auth_code_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='google_access_token',
        ),
           ]
