# Generated by Django 4.1.7 on 2024-01-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_campain_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='campain',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
     
    ]
