# Generated by Django 4.1.7 on 2024-01-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='emailid',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
       
    ]
