# Generated by Django 4.1.7 on 2024-01-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_campain_emailid_teamgallery_ratings_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='campain',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campain',
            name='emailid',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='campain',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campain',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
       
    ]
