# Generated by Django 4.1.7 on 2024-01-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webp_image', models.ImageField(unique=True, upload_to='webp_images/')),
            ],
        ),
       
    ]
