# Generated by Django 4.1.7 on 2024-01-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_imagegallery_delete_webpimage_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageGallery',
            new_name='WebPGallery',
        ),
      
    ]
