# Generated by Django 4.1.7 on 2024-01-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_coupon_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='company',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='twitter',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
