# Generated by Django 4.1.7 on 2024-01-31 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_advisor_company_advisor_twitter_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='scheduling',
            field=models.BooleanField(default=False),
        ),
        
    ]
