# Generated by Django 4.1.7 on 2024-01-31 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_advisor_scheduling_teamgallery_ratings_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='advisor',
            name='scheduling',
            field=models.BooleanField(),
        ),
        
    ]
