# Generated by Django 4.1.7 on 2024-01-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='get_review',
            field=models.BooleanField(default=True),
        ),
       migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video_link', models.URLField()),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
