# Generated by Django 4.1.7 on 2024-01-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_advisor_get_review_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='get_review',
            field=models.BooleanField(),
        ),
       
    ]
