# Generated by Django 4.1.7 on 2024-02-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='background_pattern',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='tiktok',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='youtube',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        
    ]
