# Generated by Django 4.1.7 on 2024-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_advisor_background_pattern_advisor_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='background_pattern_profile',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
            ]
