# Generated by Django 4.1.7 on 2024-02-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_advisor_background_pattern_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='description',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userlink',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userlink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        
    ]
