# Generated by Django 4.1.7 on 2024-02-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='videolink',
            name='video_link',
            field=models.URLField(unique=True),
        ),
       
    ]
