# Generated by Django 4.1.7 on 2024-02-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_remove_userlink_thumbnail_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolink',
            name='fk_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor', unique=True),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='video_link',
            field=models.URLField(),
        ),
       
    ]
