# Generated by Django 4.1.7 on 2024-02-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='userlink',
            name='title',
            field=models.CharField(default='', max_length=1024),
        ),
     
    ]
