# Generated by Django 4.1.7 on 2024-02-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
     
        migrations.AlterField(
            model_name='userlink',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
      
    ]
