# Generated by Django 4.1.7 on 2024-02-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='userlink',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
       
    ]
