# Generated by Django 4.1.7 on 2024-02-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
       
       
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
      
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(blank=True, default='Home Financing', max_length=100, null=True),
        ),
        
       
        migrations.CreateModel(
            name='ReferralEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_email', models.EmailField(blank=True, max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
