# Generated by Django 4.1.7 on 2024-02-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralemail',
            name='referral_coupon_friends',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='referralemail',
            name='referral_coupon_users',
            field=models.CharField(default='', max_length=120),
        ),
       
    ]
