# Generated by Django 4.1.7 on 2024-02-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_referralemail_referral_coupon_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='get_review',
        ),
        migrations.AddField(
            model_name='advisor',
            name='is_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='scheduling',
            field=models.BooleanField(default=True),
        ),
       
    ]
