# Generated by Django 4.1.7 on 2024-02-10 14:55

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_remove_advisor_get_review_advisor_is_review_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path),
        ),
       
    ]
