# Generated by Django 4.1.7 on 2024-02-10 15:02

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to=api.models.Services.upload_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
       
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='Home Financing', max_length=100),
        ),
       
    ]
