# Generated by Django 4.1.7 on 2024-02-13 12:22

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='advisor',
            name='background_pattern',
            field=models.CharField(blank=True, default='https://leaponmedia.s3.amazonaws.com/media/webp_images/Group_1000003406_png.webp', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='background_pattern_profile',
            field=models.CharField(blank=True, default='https://leaponmedia.s3.amazonaws.com/media/webp_images/Group_1000003412_png.webp', max_length=512, null=True),
        ),
      
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to=api.models.Services.upload_path),
        ),
       
    ]
