# Generated by Django 4.1.7 on 2024-02-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
       
        migrations.AlterField(
            model_name='advisor',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
       
        migrations.AlterField(
            model_name='review',
            name='fk_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
       
    ]
