# Generated by Django 4.1.7 on 2024-02-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_review_name_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='client',
            name='fk_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
       
    ]
