# Generated by Django 4.1.7 on 2024-02-26 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_client_address_client_email_client_name_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        
    ]
