# Generated by Django 4.1.7 on 2024-03-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_client_date_joined_teamgallery_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='campain_logos/'),
        ),
        
    ]
