# Generated by Django 4.1.7 on 2024-03-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_campain_logo_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='custom_username',
            field=models.CharField(default='', max_length=150),
        ),
       
    ]
