# Generated by Django 4.1.7 on 2024-03-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_publicreview_profile_picture_teamgallery_ratings_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='ReferralRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
                ('referred_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to='api.advisor')),
            ],
        ),
    ]
