# Generated by Django 4.1.7 on 2024-04-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_teamgallery_ratings_teamgallery_status_and_more'),
    ]

    operations = [
      
       
    ]
