# Generated by Django 4.1.7 on 2024-04-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='ApplePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applepass', models.FileField(upload_to='applepasses/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
