# Generated by Django 4.1.7 on 2024-04-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applepass',
            name='applepass',
            field=models.FileField(unique=True, upload_to='applepasses/'),
        ),
       
    ]
