# Generated by Django 4.1.7 on 2024-04-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='workinghour',
            name='timezone_offset',
            field=models.IntegerField(default='+0'),
        ),
           ]
