# Generated by Django 4.1.7 on 2024-04-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='timezone_offset',
            field=models.CharField(default='+0', max_length=3),
        ),
    ]
