# Generated by Django 4.1.7 on 2024-04-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghour',
            name='timezone_offset',
        ),
            ]
