# Generated by Django 4.1.7 on 2024-05-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        
    ]
