# Generated by Django 4.1.7 on 2024-05-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='dayName',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
