# Generated by Django 4.1.7 on 2024-05-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='workinghour',
            name='slot_time',
        ),
        
        migrations.CreateModel(
            name='AdvisorSlotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.JSONField(default=list)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
