# Generated by Django 4.1.7 on 2024-05-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='dayName',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        
    ]
