# Generated by Django 4.1.7 on 2024-05-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
       
            ]
