# Generated by Django 4.1.7 on 2024-05-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
         migrations.CreateModel(
            name='AdvisorLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(unique=True, upload_to='advisor_logo/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
       
    ]
