# Generated by Django 4.1.7 on 2024-05-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_advisorlogo_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='background_colour',
            field=models.CharField(blank=True, default='#282828', max_length=512, null=True),
        ),
        
    ]
