# Generated by Django 4.1.7 on 2024-05-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_advisorlogo_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='Payment_Status',
            field=models.BooleanField(default=False),
        ),
        
    ]
