# Generated by Django 4.1.7 on 2024-05-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        
    ]
