# Generated by Django 4.1.7 on 2024-06-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReferralRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
                ('team_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to='api.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='TeamReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
