# Generated by Django 4.1.7 on 2024-06-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_teamreferralrelationship_teamreferralcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamreferralrelationship',
            name='team_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_referred_user', to='api.advisor'),
        ),
    ]
