# Generated by Django 4.1.7 on 2024-06-03 13:50

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_alter_teamreferralrelationship_team_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path)),
                ('color', models.CharField(max_length=20, unique=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
        migrations.DeleteModel(
            name='TeamReferralCode',
        ),
    ]
