# Generated by Django 4.1.7 on 2024-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_adminadvisor_delete_teamreferralcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadvisor',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
