# Generated by Django 4.1.7 on 2024-06-03 16:15

import api.models.Services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_alter_adminadvisor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadvisor',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path),
        ),
    ]
