# Generated by Django 4.1.7 on 2024-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_alter_adminadvisor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='is_team_admin',
            field=models.BooleanField(default=False),
        ),
    ]
