# Generated by Django 4.1.7 on 2024-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_advisor_is_team_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminadvisor',
            name='team_limit',
            field=models.IntegerField(default=0),
        ),
    ]
