# Generated by Django 4.1.7 on 2024-07-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_remove_advisorslottime_slot_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminadvisor',
            name='color',
            field=models.CharField(max_length=20),
        ),
        
    ]
