# Generated by Django 4.1.7 on 2024-07-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_remove_advisorslottime_slot_time_and_more'),
    ]

    operations = [
        
    ]
