# Generated by Django 4.1.7 on 2024-07-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_remove_advisorslottime_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_SocialHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='TeamService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Powerful tactics for achieving home ownership success.', max_length=512)),
                ('desc', models.CharField(default='Discover the transformative power of proven investment strategies, offering guidance toward financial independence and the accumulation of wealth through informed decision - making.', max_length=1024)),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='TeamVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video_link', models.URLField()),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor', unique=True)),
            ],
        ),
 
    ]
