# Generated by Django 4.1.7 on 2024-07-26 13:13

import api.models.Services
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_team_socialhandle_teamlink_teamservice_teamvideolink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAdvisorGallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('pictures', models.ImageField(default=None, upload_to=api.models.Services.upload_path)),
                ('column_number', models.IntegerField()),
                ('fk_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advisor')),
            ],
        ),
    ]
