# Generated by Django 4.1.7 on 2024-07-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_teamadvisorgallery_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='team_socialhandle',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='team_socialhandle',
            name='url',
        ),
        migrations.AddField(
            model_name='team_socialhandle',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='team_socialhandle',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='team_socialhandle',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='team_socialhandle',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='team_socialhandle',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='team_socialhandle',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.RemoveField(
            model_name="publicreview",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="teamgallery",
            name="ratings",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="teamgallery",
            name="status",
            field=models.CharField(
                choices=[(0, "in_active"), (1, "active")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teamgallery",
            name="story",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="digitalcardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
            ),
        ),
        migrations.AlterField(
            model_name="exchangecontacts",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="fk_advisor",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advisors",
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="fk_member",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="workinghour",
            name="working_hour",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="Logo",
        ),
        
    ]
