# Generated by Django 4.1.7 on 2024-08-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_remove_publicreview_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='company',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='scheduling',
            field=models.BooleanField(default=False),
        ),
    ]
