# Generated by Django 4.1.7 on 2024-08-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0184_alter_advisor_company_is_review_scheduling"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="sorting_id",
            field=models.IntegerField(default=1),
        ),

        migrations.AddField(
            model_name="advisor",
            name="payment_plan",
            field=models.CharField(
                blank=True,
                choices=[(0, "monthly"), (1, "yearly")],
                max_length=10,
                null=True,
            ),
        ),

    ]
