# Generated by Django 4.1.7 on 2024-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0185_service_sorting_id_alter_advisor_payment_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="payment_plan",
            field=models.CharField(
                blank=True,
                choices=[(0, "monthly"), (1, "yearly")],
                default="",
                max_length=10,
                null=True,
            ),
        ),
    ]
