# Generated by Django 4.1.7 on 2024-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_alter_advisor_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrelationship',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
