# Generated by Django 4.1.7 on 2024-08-31 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0187_referralrelationship_is_rewarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentbilling",
            name="payment_email",
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="payment_mode",
            field=models.CharField(
                choices=[(0, "subscription"), (1, "payment"), (2, "setup")],
                default="setup",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="payment_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="payment_status",
            field=models.CharField(
                choices=[(0, "paid"), (1, "unpaid"), (2, "no_payment_required")],
                default="unpaid",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="stripe_checkout_id",
            field=models.CharField( unique=True, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="fk_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="status",
            field=models.CharField(
                choices=[(0, "open"), (1, "expired"), (2, "complete")],
                default="open",
                max_length=100,
            ),
        ),
        
    ]
