# Generated by Django 4.1.7 on 2024-09-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0188_paymentbilling_payment_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentbilling",
            name="fk_user",
        ),
        migrations.AddField(
            model_name="user",
            name="fk_payment_billing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.paymentbilling",
            ),
            preserve_default=False,
        ),
    ]
