# Generated by Django 4.1.7 on 2024-09-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0189_remove_paymentbilling_fk_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentbilling",
            name="payment_mode",
            field=models.CharField(default="setup", max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="fk_payment_billing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.paymentbilling",
            ),
        ),
    ]
