# Generated by Django 4.1.7 on 2024-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0190_alter_paymentbilling_payment_mode_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentbilling",
            constraint=models.UniqueConstraint(
                fields=("payment_email", "payment_name"),
                name="unique_email_name_combination",
            ),
        ),
    ]
