# Generated by Django 4.1.7 on 2024-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0191_paymentbilling_unique_email_name_combination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentbilling",
            name="stripe_customer_id",
            field=models.CharField(default="Null", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveConstraint(
            model_name="paymentbilling",
            name="unique_email_name_combination",
        ),
        migrations.RenameField(
            model_name="paymentbilling",
            old_name="stripe_checkout_id",
            new_name="payment_intent_id",
        ),
        migrations.RenameField(
            model_name="paymentbilling",
            old_name="payment_email",
            new_name="email",
        ),
        migrations.RemoveField(
            model_name="paymentbilling",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="paymentbilling",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="paymentbilling",
            name="payment_mode",
        ),
        migrations.RemoveField(
            model_name="paymentbilling",
            name="payment_name",
        ),
        migrations.RemoveField(
            model_name="paymentbilling",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="paymentbilling",
            name="status",
        ),
    ]
