# Generated by Django 4.1.7 on 2024-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0192_remove_paymentbilling_unique_email_name_combination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentbilling",
            name="stripe_subscription_id",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="payment_intent_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="stripe_customer_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
