# Generated by Django 4.1.7 on 2024-09-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0193_paymentbilling_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamreferralrelationship",
            name="team_advisor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_referred_user",
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="teamvideolink",
            name="fk_advisor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
            ),
        ),
        migrations.AlterField(
            model_name="videolink",
            name="fk_advisor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.advisor"
            ),
        ),
    ]
