# Generated by Django 4.1.7 on 2024-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0194_alter_teamreferralrelationship_team_advisor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                ("otpId", models.AutoField(primary_key=True, serialize=False)),
                ("otp", models.CharField(max_length=8)),
                ("email", models.EmailField(default="abc@xyz.com", max_length=254)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("create_time", models.DateTimeField()),
                ("expiry_time", models.DateTimeField()),
                ("verified", models.BooleanField(default=False)),
                ("used", models.BooleanField(default=False)),
            ],
        ),
    ]
