# Generated by Django 4.1.7 on 2024-09-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrelationship',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
