# Generated by Django 4.1.7 on 2024-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0196_referralrelationship_is_scheduled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="about",
            field=models.CharField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
    ]
