# Generated by Django 4.1.7 on 2024-09-10 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0197_alter_advisor_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentbilling",
            old_name="payment_intent_id",
            new_name="set_up_intent_id",
        ),
    ]
