# Generated by Django 4.1.7 on 2024-09-11 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0198_rename_payment_intent_id_paymentbilling_set_up_intent_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeDetails",
            fields=[
                (
                    "stripe_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateField(default=django.utils.timezone.now)),
                ("status", models.BooleanField(default=True)),
                ("product_name", models.CharField(max_length=255)),
                ("desc", models.CharField(blank=True, max_length=1024, null=True)),
                ("trial_days", models.IntegerField(blank=True, default=14, null=True)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, null=True
                    ),
                ),
                ("monthly_price_id", models.CharField(default=None, max_length=512)),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, null=True
                    ),
                ),
                ("yearly_price_id", models.CharField(default=None, max_length=512)),
                ("coupon", models.JSONField(default=list)),
            ],
        ),
    ]
