# Generated by Django 4.1.7 on 2024-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0199_stripedetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripedetails",
            name="product_id",
            field=models.CharField(default="abc", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stripedetails",
            name="monthly_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stripedetails",
            name="monthly_price_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stripedetails",
            name="yearly_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stripedetails",
            name="yearly_price_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="stripedetails",
            name="coupon",
        ),
    ]
