# Generated by Django 4.1.7 on 2024-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_stripedetails_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
