# Generated by Django 4.1.7 on 2024-10-15 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0202_alter_user_options_profileprogress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="fk_user",
        ),
        migrations.RemoveField(
            model_name="businessstatistics",
            name="fk_advisor",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="fk_advisor",
        ),
        migrations.RemoveField(
            model_name="custom",
            name="fk_advisor",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="fk_advisor",
        ),
        migrations.RemoveField(
            model_name="products",
            name="fk_service",
        ),
        migrations.RemoveField(
            model_name="reviewhighlight",
            name="fk_advisor",
        ),
        migrations.RemoveField(
            model_name="reviewhighlight",
            name="fk_review",
        ),
        migrations.RemoveField(
            model_name="serviceclient",
            name="fk_client",
        ),
        migrations.RemoveField(
            model_name="serviceclient",
            name="fk_service",
        ),
        migrations.RemoveField(
            model_name="servicecompany",
            name="fk_company",
        ),
        migrations.RemoveField(
            model_name="servicecompany",
            name="fk_service",
        ),
        migrations.DeleteModel(
            name="Templates",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="BusinessStatistics",
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Custom",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
        migrations.DeleteModel(
            name="ReviewHighlight",
        ),
        migrations.DeleteModel(
            name="ServiceClient",
        ),
        migrations.DeleteModel(
            name="ServiceCompany",
        ),
    ]
