# Generated by Django 4.1.7 on 2024-10-15 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0203_remove_blog_fk_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
