# Generated by Django 4.1.7 on 2024-10-22 15:42

import api.models.Services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0204_delete_subscription"),
    ]

    operations = [

        migrations.RemoveField(
            model_name="advisor",
            name="completed_session",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="description",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="passive_generated_income",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="professional_trained",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="quote",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="region_of_operation",
        ),
        migrations.RemoveField(
            model_name="advisor",
            name="response_rate",
        ),

        migrations.RemoveField(
            model_name="advisor",
            name="total_seminar",
        ),
        migrations.AddField(
            model_name="user",
            name="team_member_count",
            field=models.CharField(max_length=10, null=True, blank=True, default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="Payment_Status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="app_password",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="background_colour",
            field=models.CharField(
                blank=True, default="#282828", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="background_pattern",
            field=models.CharField(
                blank=True,
                default="https://leaponmedia.s3.amazonaws.com/media/webp_images/Group_1000003406_png.webp",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="background_pattern_profile",
            field=models.CharField(
                blank=True,
                default="https://leaponmedia.s3.amazonaws.com/media/webp_images/Group_1000003412_png.webp",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="custom_username",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fk_package",
            field=models.ForeignKey(
                default=5, on_delete=django.db.models.deletion.CASCADE, to="api.package"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_team_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_team_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=api.models.Services.upload_path,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="meet_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_size",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_plan",
            field=models.CharField(
                blank=True,
                choices=[(0, "monthly"), (1, "yearly")],
                default="",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="platform",
            field=models.CharField(
                blank=True, default="gmail", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="purpose",
            field=models.TextField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="scheduling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="source",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tiktok",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
    ]
