# Generated by Django 4.1.7 on 2024-10-23 15:13

import api.models.Services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0206_rename_usergallery_advisorgallery_and_more"),
    ]

    operations = [
migrations.AlterField(
            model_name="notereminder",
            name="note_status",
            field=models.IntegerField(
                choices=[(-1, "Not Added"), (0, "Deleted"), (1, "Active")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="notereminder",
            name="reminder_status",
            field=models.IntegerField(
                choices=[(-1, "Not Added"), (0, "Deleted"), (1, "Active")], default=0
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reschedule_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="fk_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.client",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("deleted", "deleted"),
                    ("active", "active"),
                    ("completed", "completed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="update_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="update_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add", "Add"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("email", "Email"),
                            ("schedule_meeting", "Schedule Meeting"),
                            ("reschedule_meeting", "Reschedule Meeting"),
                            ("delete_meeting", "Delete Meeting"),
                            ("add_note", "Add Note"),
                            ("update_note", "Update Note"),
                            ("delete_note", "Delete Note"),
                            ("add_reminder", "Add Reminder"),
                            ("update_reminder", "Update Reminder"),
                            ("delete_reminder", "Delete Reminder"),
                            ("tag", "Tag/Label Change"),
                            ("archive", "Archive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
                ("email_id", models.IntegerField(blank=True, null=True)),
                ("note_id", models.IntegerField(blank=True, null=True)),
                ("reminder_id", models.IntegerField(blank=True, null=True)),
                ("meeting_id", models.IntegerField(blank=True, null=True)),
                ("tag_id", models.IntegerField(blank=True, null=True)),
                (
                    "fk_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.contact",
                    ),
                ),
                (
                    "fk_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("email_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("thread_link", models.URLField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("is_bulk", models.BooleanField(default=False)),
                (
                    "fk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(related_name="emails", to="api.contact"),
                ),
            ],
        ),

        migrations.AddField(
            model_name="appointment",
            name="fk_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.contact",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="fk_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.Services.contact_upload_path
            ),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Payment_Status",
            new_name="payment_status",
        ),
        
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.IntegerField(choices=[(0, "Free"), (1, "Paid")], default=0),
        ),

        migrations.AlterField(
            model_name="businesscardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="digitalcardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="receivecardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),

        migrations.AlterField(
            model_name="businesscardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="digitalcardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="receivecardemail",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="email",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),

    ]
