# Generated by Django 4.1.7 on 2024-11-12 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0208_remove_advisor_team_member_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacttag",
            old_name="contact",
            new_name="fk_contact",
        ),
        migrations.RenameField(
            model_name="contacttag",
            old_name="tag",
            new_name="fk_tag",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="info",
            new_name="info_desc",
        ),
        migrations.AddField(
            model_name="tag",
            name="info_title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="advisorgallery",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="advisorlogo",
            name="fk_advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="notereminder",
            name="note_status",
            field=models.IntegerField(
                choices=[(-1, "Not Added"), (0, "Deleted"), (1, "Active")], default=-1
            ),
        ),
        migrations.AlterField(
            model_name="notereminder",
            name="reminder_status",
            field=models.IntegerField(
                choices=[(-1, "Not Added"), (0, "Deleted"), (1, "Active")], default=-1
            ),
        ),
        migrations.AlterField(
            model_name="teamreferralrelationship",
            name="team_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_referred_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teamvideolink",
            name="fk_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="videolink",
            name="fk_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contacttag",
            unique_together={("fk_contact", "fk_tag")},
        ),
    ]
