# Generated by Django 4.1.7 on 2024-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0209_rename_contact_contacttag_fk_contact_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="work",
            new_name="company",
        ),
        migrations.AddField(
            model_name="contact",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
