# Generated by Django 4.1.7 on 2024-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0210_rename_work_contact_company_contact_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.RenameField(
            model_name="notereminder",
            old_name="contact",
            new_name="fk_contact",
        ),
        migrations.RenameField(
            model_name="notereminder",
            old_name="user",
            new_name="fk_user",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="user",
            new_name="fk_user",
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("fk_user", "name")},
        ),

    ]
