# Generated by Django 4.1.7 on 2024-11-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0211_contact_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notereminder",
            name="image",
        ),
        migrations.AddField(
            model_name="notereminder",
            name="editable",
            field=models.IntegerField(choices=[(0, "False"), (1, "True")], default=1),
        ),
        migrations.AddField(
            model_name="notereminder",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="pfp_color",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="generated_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("update", "Update"),
                    ("archive", "Archive"),
                    ("email", "Email"),
                    ("schedule_meeting", "Schedule Meeting"),
                    ("reschedule_meeting", "Reschedule Meeting"),
                    ("delete_meeting", "Delete Meeting"),
                    ("note", "Note"),
                    ("reminder", "Reminder"),
                    ("note_reminder", "Note Reminder"),
                    ("tag", "Tag/Label Change"),
                    ("restore", "Restore"),
                    ("call", "Call")
                ],
                max_length=20,
            ),
        ),
    ]
