# Generated by Django 4.1.7 on 2024-11-19 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_remove_notereminder_image_notereminder_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.TextField()),
                ('refreshtoken', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('fk_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advisorappointment',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('deleted', 'deleted'), ('active', 'active'), ('completed', 'completed'),
                                            ('canceled', 'canceled')], default='active', max_length=10),
        ),
    ]
