# Generated by Django 4.1.7 on 2024-12-02 13:51

from django.db import migrations, models
import django.db.models.deletion
import api.models.Services


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_outlook_user_google_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('deleted', 'deleted'), ('active', 'active'), ('completed', 'completed'), ('canceled', 'canceled'), ('reschedule', 'reschedule')], default='active', max_length=10),
        ),
        migrations.RemoveField(
            model_name="notereminder",
            name="images",
        ),
        migrations.CreateModel(
            name="NoteReminderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=api.models.Services.notes_upload_path)),
                (
                    "fk_note_reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.notereminder",
                    ),
                ),
            ],
        ),
    ]
