# Generated by Django 4.1.7 on 2024-12-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0214_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="profile_pic",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
