# Generated by Django 4.1.7 on 2024-12-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0215_alter_contact_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
