# Generated by Django 4.1.7 on 2025-01-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0217_caldav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fcm_token",
            field=models.JSONField(default=list),
        ),
    ]
