# Generated by Django 4.1.7 on 2025-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_alter_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_meet',
            field=models.BooleanField(default=False),
        ),
    ]
