# Generated by Django 4.1.7 on 2025-02-17 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0219_user_google_meet"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_permission",
            field=models.IntegerField(
                choices=[(-1, "Default"), (0, "False"), (1, "True")], default=-1
            ),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_zip', models.CharField(max_length=20)),
                ('billing_country', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_zip', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'fk_user',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
