# Generated by Django 4.1.7 on 2025-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_leaponsmartcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='eventId',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
