# Generated by Django 4.1.7 on 2025-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_appointment_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avaialability_added_first_time',
            field=models.BooleanField(default=False),
        ),
    ]
