# Generated by Django 4.1.7 on 2025-04-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0225_userfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripedetails",
            name="quarterly_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stripedetails",
            name="quarterly_price_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
