# Generated by Django 4.1.7 on 2025-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0226_stripedetails_quarterly_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_meta_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
