# Generated by Django 4.1.7 on 2025-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0227_alter_user_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, default="", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(
                blank=True, default="Mr.", max_length=1024, null=True
            ),
        ),
    ]
