# Generated by Django 4.2.20 on 2025-05-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_alter_user_address_alter_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caldav',
            name='platform',
            field=models.CharField(default='', max_length=100),
        ),
    ]
