# Generated by Django 4.2.20 on 2025-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_profilevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldav',
            name='password',
            field=models.TextField(),
        ),
    ]
