# Generated by Django 4.2.20 on 2025-05-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_alter_caldav_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
