# Generated by Django 4.1.7 on 2025-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0232_service_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlink",
            name="sorting_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="substack",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
    ]
