# Generated by Django 4.2.20 on 2025-06-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_userfcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfcmtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
    ]
