# Generated by Django 4.2.20 on 2025-06-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_userfcmtoken_ip_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfcmtoken',
            unique_together={('user', 'ip_address')},
        ),
    ]
