# Generated by Django 4.1.7 on 2025-06-26 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0236_alter_userfcmtoken_unique_together"),
    ]

    operations = [

        migrations.AddField(
            model_name="paymentbilling",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="is_subscription",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentbilling",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="set_up_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="stripe_customer_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentbilling",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
