# Generated by Django 4.1.7 on 2025-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0237_alter_paymentbilling_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripedetails",
            name="one_time_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stripedetails",
            name="one_time_price_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
