# Generated by Django 4.2.20 on 2025-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_pattern',
            field=models.CharField(blank=True, default='https://leapon-media.s3.amazonaws.com/media/webp_images/Group_1000003406_png.webp', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_pattern_profile',
            field=models.CharField(blank=True, default='https://leapon-media.s3.amazonaws.com/media/webp_images/Group_1000003412_png.webp', max_length=512, null=True),
        ),
    ]
