# Generated by Django 4.2.20 on 2025-08-01 16:31

import api.models.Services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_alter_user_background_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('profile_picture', models.ImageField(upload_to=api.models.Services.upload_path)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('tiktok', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('background_pattern', models.CharField(blank=True, default='https://leapon-media.s3.amazonaws.com/media/webp_images/Group_1000003406_png.webp', max_length=512, null=True)),
                ('background_pattern_profile', models.CharField(blank=True, default='https://leapon-media.s3.amazonaws.com/media/webp_images/Group_1000003412_png.webp', max_length=512, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Services.upload_path)),
                ('card_name', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('background_colour', models.CharField(blank=True, default='#282828', max_length=512, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
