# Generated by Django 4.1.7 on 2025-08-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comments', models.CharField(max_length=512)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('fk_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contact')),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
    ]
