# Generated by Django 4.1.7 on 2025-08-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_profilesreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avaialability_added_first_time',
            new_name='availability_added_first_time',
        ),
        migrations.AddField(
            model_name='profiles',
            name='wlcm_message',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='wlcm_message',
            field=models.JSONField(default=dict),
        ),
    ]
