# Generated by Django 4.1.7 on 2025-08-26 15:29

import api.models.Services
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_rename_avaialability_added_first_time_user_availability_added_first_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(0, 'in_active'), (1, 'active')], default='active', max_length=10)),
                ('pictures', models.ImageField(default=None, upload_to=api.models.Services.upload_path)),
                ('column_number', models.IntegerField()),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
    ]
