# Generated by Django 4.2.20 on 2025-08-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_rename_avaialability_added_first_time_user_availability_added_first_time_and_more'),
        ('api', '0244_profilesgallery'),
    ]

    operations = [
    ]
