# Generated by Django 4.2.20 on 2025-08-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0245_merge_0243_service_service_img_0244_profilesgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Powerful tactics for achieving home ownership success.', max_length=512)),
                ('desc', models.CharField(default='Discover the transformative power of proven investment strategies, offering guidance toward financial independence and the accumulation of wealth through informed decision - making.', max_length=1024)),
                ('sorting_id', models.IntegerField(default=1)),
                ('url', models.CharField(default='', max_length=512)),
                ('service_img', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
         migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service_images/'),
        ),
    ]
