# Generated by Django 4.1.7 on 2025-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_profilesservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='applepass',
            name='username',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='applepass',
            constraint=models.UniqueConstraint(fields=('fk_user', 'username'), name='unique_user_username'),
        ),
    ]
