# Generated by Django 4.1.7 on 2025-10-12 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_applepass_username_applepass_unique_user_username'),
    ]

    operations = [

        migrations.AddField(
            model_name='profilevisit',
            name='fk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profiles'),
        ),
        migrations.AlterField(
            model_name='profilevisit',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='profilevisit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('fk_user__isnull', False), ('fk_profile__isnull', True)), models.Q(('fk_user__isnull', True), ('fk_profile__isnull', False)), _connector='OR'), name='only_one_of_user_or_profile_visit'),
        ),
        migrations.AddConstraint(
            model_name='profilevisit',
            constraint=models.UniqueConstraint(fields=('session_key', 'fk_user'), name='unique_user_visit'),
        ),
        migrations.AddConstraint(
            model_name='profilevisit',
            constraint=models.UniqueConstraint(fields=('session_key', 'fk_profile'), name='unique_profile_visit'),
        ),
        migrations.CreateModel(
            name='ProfileVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('upload_video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userlink',
            name='fk_advisor',
        ),
        migrations.AddField(
            model_name='userlink',
            name='fk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.profiles'),
        ),
        migrations.AddField(
            model_name='videolink',
            name='upload_video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='userlink',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('fk_user__isnull', False), ('fk_profile__isnull', True)),
                               models.Q(('fk_user__isnull', True), ('fk_profile__isnull', False)), _connector='OR'),
                name='only_one_of_user_or_profile'),
        ),
        migrations.AddField(
            model_name='profilevideolink',
            name='fk_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='api.profiles'),
        ),
        migrations.AddField(
            model_name='profilevideolink',
            name='fk_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_video_user',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
