# Generated by Django 4.1.7 on 2025-10-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0248_alter_profilevisit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='logo',
        ),
        migrations.CreateModel(
            name='AdvisorProfileLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(unique=True, upload_to='profile_logo/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profiles')),
            ],
        ),
    ]
