# Generated by Django 4.1.7 on 2025-10-14 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_remove_profiles_logo_advisorprofilelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1024)),
                ('agent_name', models.CharField(default='', max_length=512)),
                ('secret_key', models.CharField(default='', max_length=1024)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='profilevisit',
            name='unique_user_visit',
        ),
        migrations.RemoveConstraint(
            model_name='profilevisit',
            name='unique_profile_visit',
        ),

        migrations.AddConstraint(
            model_name='profilevisit',
            constraint=models.UniqueConstraint(fields=('session_key', 'fk_user', 'ip_address'),
                                               name='unique_user_visit'),
        ),
        migrations.AddConstraint(
            model_name='profilevisit',
            constraint=models.UniqueConstraint(fields=('session_key', 'fk_profile', 'ip_address'),
                                               name='unique_profile_visit'),
        ),
    ]
