# Generated by Django 4.1.7 on 2025-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_alter_profilevisit_unique_together_agent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilevisit',
            unique_together=set(),
        ),
    ]
