# Generated by Django 4.1.7 on 2025-10-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0251_alter_profilevisit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_review',
            field=models.BooleanField(default=True),
        ),
    ]
