# Generated by Django 4.1.7 on 2025-10-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0252_profiles_is_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_username',
            field=models.CharField(default='', max_length=512),
        ),
    ]
