# Generated by Django 4.2.20 on 2025-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0254_profiles_is_feature_images_profiles_is_feature_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileservice',
            name='service_img',
            field=models.ImageField(blank=True, default='webp_images/713b6961fe564b5492ed32860ddcd633.webp', null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.ImageField(blank=True, default='webp_images/713b6961fe564b5492ed32860ddcd633.webp', null=True, upload_to='service_images/'),
        ),
    ]
