# Generated by Django 4.2.20 on 2025-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0255_alter_profileservice_service_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='is_feature_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_feature_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_feature_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_feature_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_service',
            field=models.BooleanField(default=True),
        ),
    ]
