# Generated by Django 4.2.20 on 2025-11-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0256_alter_profiles_is_feature_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorgallery',
            name='column_number',
        ),
        migrations.RemoveField(
            model_name='profilesgallery',
            name='column_number',
        ),
    ]
