# Generated by Django 4.1.7 on 2025-11-28 16:23

from django.db import migrations, models
from django.conf import settings
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0257_remove_advisorgallery_column_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_order', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='profile_layout', to='api.profiles')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_layout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profilelayout',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('fk_profile__isnull', True), ('fk_user__isnull', False)),
                               models.Q(('fk_profile__isnull', False), ('fk_user__isnull', True)), _connector='OR'),
                name='only_one_fk_must_exist'),
        ),
        migrations.AlterField(
            model_name='profilevideolink',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_video_user',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_user',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
