# Generated by Django 4.2.20 on 2025-11-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0258_profilelayout_profilelayout_only_one_fk_must_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='language',
            field=models.CharField(default='en-US', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='twilio_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice_id',
            field=models.CharField(default='cjVigY5qzO86Huf0OWal', max_length=100),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='agent_name',
            new_name='agent_id',
        ),
        migrations.AddField(
            model_name='agent',
            name='client_name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
