# Generated by Django 4.1.7 on 2026-01-05 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0259_agent_created_at_agent_language_agent_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='public_id',
            field=models.UUIDField(null=True,
        blank=True,
        db_index=True,
        editable=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
