# Generated by Django 4.1.7 on 2026-01-05 18:53

from django.db import migrations
import uuid

from django.utils.text import slugify


def populate_public_id(apps, schema_editor):
    Contact = apps.get_model("api", "Contact")
    for contact in Contact.objects.filter(public_id__isnull=True):
        contact.public_id = uuid.uuid4()
        contact.slug = slugify(contact.name)
        contact.save(update_fields=["public_id"])

def reverse_populate_public_id(apps, schema_editor):
    Contact = apps.get_model("api", "Contact")
    Contact.objects.update(public_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0260_contact_public_id_contact_slug'),
    ]

    operations = [
        migrations.RunPython(populate_public_id,
                             reverse_code=reverse_populate_public_id,),
    ]
