# Generated by Django 4.1.7 on 2026-01-05 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0261_backfill_contact_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4,
        editable=False,
        unique=True,
        db_index=True),
        ),
    ]
