# Generated by Django 4.1.7 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0263_contactshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripedetails',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
    ]
