# Generated by Django 4.1.7 on 2026-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_alter_stripedetails_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reengagement_sent',
            field=models.BooleanField(default=False),
        ),
    ]
