# Generated by Django 4.1.7 on 2026-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0265_contact_reengagement_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCardIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('card_type', models.CharField(max_length=50)),
                ('logo', models.ImageField(default=None, unique=True, upload_to='advisor_logo/'),),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='smartcardintent',
            name='logo',
            field=models.ImageField(unique=True, upload_to='advisor_logo/'),
        ),
    ]
