# Generated by Django 4.1.7 on 2026-02-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_smartcardintent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reengagement_sent',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_reengagement_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),

    ]
