# Generated by Django 4.1.7 on 2026-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0267_remove_contact_reengagement_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_weekly_insight_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_weekly_views_count',
            field=models.IntegerField(default=0),
        ),
    ]
