# Generated by Django 4.1.7 on 2026-02-27 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0268_user_last_weekly_insight_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('mobile', 'Mobile'), ('personal', 'Personal'), ('work', 'Work'), ('other', 'Other')], default='office', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='api.profiles')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_contact_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
