# Generated by Django 4.1.7 on 2026-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_profilecontactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcardintent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='advisor_logo/'),
        ),
    ]
