# Generated by Django 4.1.7 on 2026-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0272_appointment_start_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reengagement_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
