# Generated by Django 4.1.7 on 2026-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0273_last_reengagement_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.FloatField()),
                ('deposit_amount', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('deposit_paid', models.BooleanField(default=False)),
                ('remaining_paid', models.BooleanField(default=False)),
                ('auto_charge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

    ]
