# Generated by Django 4.1.7 on 2026-03-31 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0274_order'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='contact',
            name='created_from',
            field=models.CharField(default="Manual", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(default='Manually', max_length=50),
            preserve_default=False,
        ),
    ]
