# Generated by Django 4.1.7 on 2026-04-02 16:57

import api.models.Services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('is_user', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.URLField(blank=True, max_length=2048, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=api.models.Services.contact_upload_path)),
                ('is_profile_pic', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_details', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pfp_color', models.TextField(blank=True, null=True)),
                ('generated_text', models.TextField(blank=True, null=True)),
                ('last_reengagement_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_from', models.CharField(max_length=50)),
                ('fk_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_contacts', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='potentialcontact',
            constraint=models.UniqueConstraint(fields=('email', 'owner'), name='unique_potential_contact_per_user'),
        ),
    ]
