# Generated by Django 4.1.7 on 2026-04-09 03:37

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_potentialcontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialcontact',
            name='fk_client',
        ),
        migrations.RemoveField(
            model_name='potentialcontact',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='potentialcontact',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='potentialcontact',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='potentialcontact',
            name='public_id',
        ),
        migrations.AddField(
            model_name='timeline',
            name='fk_potential_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='timeline', to='api.potentialcontact'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='fk_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='activities', to='api.contact'),
        ),
        migrations.AddField(
            model_name='email',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
