# Generated by Django 4.1.7 on 2026-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0278_remove_potentialcontact_fk_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='email',
            name='provider',
            field=models.CharField(default='gmail', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='to_email',
            field=models.TextField(null=True),
        ),
    ]
