# Generated by Django 4.1.7 on 2026-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0281_remove_email_thread_id_email_fk_thread'),
    ]

    operations = [


        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
