# Generated by Django 4.1.7 on 2026-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_remove_advisor_fk_package_remove_advisor_fk_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='background_pattern',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/leapon-db-storage-public/media/webp_images/Group_1000003406_png.webp', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='background_pattern_profile',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/leapon-db-storage-public/media/webp_images/Group_1000003412_png.webp', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_pattern',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/leapon-db-storage-public/media/webp_images/Group_1000003406_png.webp', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_pattern_profile',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/leapon-db-storage-public/media/webp_images/Group_1000003412_png.webp', max_length=512, null=True),
        ),
    ]
